name: custom_dropdown_2
description: A custom dropdown, forked from animated_custom_dropdown.
author: Ismael Correia
homepage: https://github.com/ismaelcorreia/custom_drop_down_2
repository: https://github.com/ismaelcorreia/custom_drop_down_2


version: 1.0.0+3

environment:
  sdk: '>=3.1.0 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:

  uses-material-design: true

